const questions = [
    { word: 'anyway(副)', meanings: ['とにかく'] ,},
    { word: 'following(前)', meanings: ['～に続いて'] },
    { word: 'following(形)', meanings: ['次の','以下の'] },
    { word: 'refer(動)', meanings: ['参照する','言及する','紹介する'] },
    { word: 'available(形)', meanings: ['入手できる','利用できる'] },
    { word: 'department(名)', meanings: ['部門','売り場'] },
    { word: 'conference(名)', meanings: ['会議'] },
    { word: 'according to(前)', meanings: ['～によると','～に従って'] },
    { word: 'likely(副)', meanings: ['おそらく'] },
    { word: 'likely(形)', meanings: ['～しそうだ'] },
    { word: 'offer(動)', meanings: ['申し出る','提供する'] },
    { word: 'offer(名)', meanings: ['オファー','申し出'] },
    { word: 'equipment(名)', meanings: ['機器','装備'] },
    { word: 'provide(動)', meanings: ['提供する'] },
    { word: 'local(形)', meanings: ['地元の'] },
    { word: 'purchase(動)', meanings: ['購入する'] },
    { word: 'purchase(名)', meanings: ['購入品'] },
    { word: 'opening(名)', meanings: ['空き','開店'] },
    { word: 'construction(名)', meanings: ['建設'] },
    { word: 'tour(動)', meanings: ['見学する','旅行する'] },
    { word: 'tour(名)', meanings: ['見学','旅行'] },
    { word: 'research(名)', meanings: ['研究','調査'] },
    { word: 'research(動)', meanings: ['研究する','調査する'] },
    { word: 'attend(動)', meanings: ['出席する','参加する'] },
    { word: 'delivery(名)', meanings: ['配達','配達物'] },
    { word: 'recently(副)', meanings: ['最近'] },
];
